export const browserCoreExamples = [
  "kimibot browser status",
  "kimibot browser start",
  "kimibot browser stop",
  "kimibot browser tabs",
  "kimibot browser open https://example.com",
  "kimibot browser focus abcd1234",
  "kimibot browser close abcd1234",
  "kimibot browser screenshot",
  "kimibot browser screenshot --full-page",
  "kimibot browser screenshot --ref 12",
  "kimibot browser snapshot",
  "kimibot browser snapshot --format aria --limit 200",
  "kimibot browser snapshot --efficient",
  "kimibot browser snapshot --labels",
];

export const browserActionExamples = [
  "kimibot browser navigate https://example.com",
  "kimibot browser resize 1280 720",
  "kimibot browser click 12 --double",
  'kimibot browser type 23 "hello" --submit',
  "kimibot browser press Enter",
  "kimibot browser hover 44",
  "kimibot browser drag 10 11",
  "kimibot browser select 9 OptionA OptionB",
  "kimibot browser upload /tmp/file.pdf",
  'kimibot browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "kimibot browser dialog --accept",
  'kimibot browser wait --text "Done"',
  "kimibot browser evaluate --fn '(el) => el.textContent' --ref 7",
  "kimibot browser console --level error",
  "kimibot browser pdf",
];
